spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost/tests
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:/mappers/*Mapper.xml
  type-aliases-package: com.jx.Beans
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
